import React from "react";
import AuthHeader from "../../../common/navigation/authHeader";
import styles from "../../../styles/create.module.css";
import Image from "next/image";
import singleImage from "../../../public/images/single_unselect.png";
import multipleImage from "../../../public/images/multiple_unselect.png";
import Head from "next/head";
import Link from "next/link";
import withAuth from "../../../helpers/hoc";
 function Create() {
  return (
    <div>
      <Head>
      <title>Create Collections</title>
          <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container">
        <AuthHeader />
        <div className={styles.create_main}>
          <h2 className={styles.create_bold}>
            Create <span className={styles.create_head}>&nbsp;Collections</span>
          </h2>
          <p className={styles.create_para}>
            Choose “Single” if you want your collectible to be one of a kind or
            “Multiple” if you want to sell one collectible times.
          </p>
        </div>
        
          <ul className={styles.collections}>
            <Link href ='/dashboard/create/single/singleFixed'>
            <li className={styles.single}>
              <Image src={singleImage} alt="Single Image" className={styles.single_Image}></Image>
              <h6 className={styles.singleFont}>Single</h6>
            </li>
            </Link>
            <Link href='/dashboard/create/multiple/multiFixed'>
            <li className={styles.single}>
              
              <Image src={multipleImage} alt="Multiple Image" className={styles.single_Image}></Image>
              <h6 className={styles.singleFont}>Multiple</h6>
            </li>
            </Link>
          </ul>
     
      </div>
    </div>
  );
}
export default withAuth(Create)