version: "3"

services:
  client:
    container_name: syn-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      HOST: 0.0.0.0
    ports:
      - 6008:6008
    volumes:
      - ./:/src/syn/app/web
    working_dir: /src/client/app
    env_file:
      - ./.env
