import React from "react";
import styles from "../../../styles/feeds.module.css";
import Head from "next/head";
import Image from "next/image";
import feed_post from "/public/images/feeds_image.png";
import feed_profile_img from "../../../public/images/Emily Reyes.png";
import comment_img from "../../../public/images/Diane1.png";
import unlike_img from "../../../public/images/heart_line_unlike_comment.png";
import like_img from "../../../public/images/heart_like.png";
import close from "../../../public/images/close2.svg";
import profile from "../../../public/images/Yolanda.png";
import { useState,useEffect } from "react";
import { useDispatch,useSelector } from "react-redux";
import userImage from "../../../public/images/userImage.png";
import { getAllCommentAction } from "../../../action/dashboardActions";
export default function Comment(props) {
  //initial state:
  const [list ,setList] = useState([])
  const [filterList, setFilterLIst] = useState([])
  //state for post id:
  const [postId, setPostId] = useState();
  const [userProfile, setUserProfile] = useState('')
  const [userName, setUserName] = useState('')
  const [postDescription, setPostDescription] = useState('')
  const [twitter, setTwitter] = useState('')
  const [postImage,setPostImage] = useState('')
  const dispatch = useDispatch()
  //acessing id:
  useEffect(() => {
    setPostId(props.id);
    setUserName(props.name)
    setUserProfile(props.photo)
    setPostDescription(props.desc)
    setTwitter(props.twitterName)
    setPostImage(props.postPicture)
  }, []);
//handling toggling:
  const parentCommentToggle =()=>{
    props.commentToggle()
  }
  useEffect(()=>{
    const commentDetails = {
      post_id: props.id,
    }; 
    // console.log("payload###",commentDetails)
   dispatch(getAllCommentAction(commentDetails))
  },[])
  //getting data from redux
  const commentList = useSelector((state) => state.commentReducer.getCommentApi);
  // console.log("listttttt55",(commentList))
  useEffect(()=>{
    if(commentList){
      setList(commentList.results)
  // setList(commentList[postId])
    }
  },[commentList])
  // console.log("&&",list)
  return (
    <div className="container">
      <Head>
        <title>Comments</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.main_div_comments}>
        <div className={styles.sub_comment_div}>
          <div className={styles.main_details}>
            <div className={styles.left_side_image}>
              {/* <img src={feed_post} alt="" /> */}
              <Image
                src={postImage?postImage:feed_post}
                alt="feeds_post"
                height={920}
                width={718}     
              ></Image>
            </div>
            <div className={styles.right_side_comment_div}>
              <div className={styles.right_padding}>
                <div className={styles.upper_section_div}>
                  <div className={styles.sub_upper_div}>
                    <Image src={userProfile?userProfile: userImage} alt="img"
                     height={58}
                     width={58}></Image>
                  </div>
                  <div className={styles.close_img_div}>
                    <div className={styles.sub_upper_details}>
                      <h2 className={styles.sub_upper_head}>{userName}</h2>
                      <h6 className={styles.sub_para_head}>{twitter?twitter:""}</h6>
                    </div>
                    <div className={styles.close_img_wrap} >
                      <Image src={close} alt="close_img" onClick={parentCommentToggle}></Image>
                    </div>
                  </div>
                </div>
                <div className={styles.sub_para_div}>
                  <p className={styles.sub_div_para}>
                    {postDescription?postDescription: ""}
                  </p>
                </div>
                <span className={styles.lineHR_comment}></span>
                <div className={styles.comment_container}>
                  {list?.map((el,index)=>(
                  <div className={styles.sub_container} key={index}>
                    <div className={styles.sub_upper_container}>
                      <div className={styles.comment_wrap}>
                        <Image
                          src={el.profile_photo?el.profile_photo:comment_img}
                          alt={"user_comment_img"}
                          height={35}
                          width={35}
                        ></Image>
                        <h6 className={styles.sub_upper_container_head}>
                         {el.full_name?el.full_name:""}
                        </h6>
                      </div>

                      <div className="unlike">
                        <Image
                          src={unlike_img}
                          alt="unlike-img"
                          height={18}
                          width={18}
                        ></Image>
                      </div>
                    </div>
                   
                    <div className={styles.para_comment}>
                      <p className={styles.sub_upper_container_Para}>
                    {el.comment}
                      </p>

                      <span className={styles.sub_comment_para}>
                        <h6 className={styles.span_time}>10m</h6>
                        <h6 className={styles.span_time}>2likes</h6>
                        <h6 className={styles.span_time}>Reply</h6>
                      </span>
                      <span>
                        <h6 className={styles.replies}>Hide replies</h6>
                      </span>
                    </div>
                  </div>
                     ))} 
                </div>
              </div>{" "}
                {/* <div className={styles.comment_wrapper2}>
                  <div style={{ display: "flex" }}>
                    <Image
                      src={profile}
                      alt=""
                    
                      className={styles.profile_cover}
                    ></Image>

                    <div className={styles.post_text}>
                      <input
                        type="text"
                        className={styles.comment_box}
                        placeholder="Write your comment"
                      />
                      <button className={styles.comment_btn}>post</button>
                    </div>
                  </div>
                </div> */}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
