import React from "react";
import styles from "../../../styles/dashboardprofile.module.css";
import AuthHeader from "../../../common/navigation/authHeader";
import Head from "next/head";
import Image from "next/image";
import message_profile from "../../../public/images/Diane1.png";
import smallTICK from "../../../public/images/tick.svg";
import yolanda1 from "../../../public/images/yolanda1.png";
import user from "../../../public/images/user.png";
export default function Message() {
  return (
    <div>
      <Head>
        <title>Message</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container">
        <AuthHeader />
        <div className={styles.main_message}>
          <div className={styles.wrapper_message}>
            <div className={styles.left_message}>
              <div className={styles.Head}>
                <h6 className={styles.Head_msg}>Messages</h6>
              </div>
              <div className={styles.wrap_div}>
                <div className={styles.messageBOX}>
                  <div className={styles.message_div}>
                    <figure>
                      <Image
                        src={message_profile}
                        alt=""
                        className={styles.message_profile}
                      ></Image>
                    </figure>
                    <figcaption className="w-100">
                      <h6 className={styles.messageHead}>
                        Diane
                        <Image
                          src={smallTICK}
                          alt=""
                          className={styles.small_tick}
                        ></Image>
                      </h6>
                      <div className={styles.comman_msg}>
                        <p className={styles.message_para}>
                          Sent you a message
                        </p>
                        <span className={styles.timer}>54m</span>
                      </div>
                    </figcaption>
                  </div>
                </div>
                <div className={styles.messageBOX}>
                  <div className={styles.message_div}>
                    <figure>
                      <Image
                        src={message_profile}
                        alt=""
                        className={styles.message_profile}
                      ></Image>
                    </figure>
                    <figcaption className="w-100">
                      <h6 className={styles.messageHead}>
                        Diane
                        <Image
                          src={smallTICK}
                          alt=""
                          className={styles.small_tick}
                        ></Image>
                      </h6>
                      <div className={styles.comman_msg}>
                        <p className={styles.message_para}>
                          Sent you a message
                        </p>
                        <span className={styles.timer}>54m</span>
                      </div>
                    </figcaption>
                  </div>
                </div>
                <div className={styles.messageBOX}>
                  <div className={styles.message_div}>
                    <figure>
                      <Image
                        src={message_profile}
                        alt=""
                        className={styles.message_profile}
                      ></Image>
                    </figure>
                    <figcaption className="w-100">
                      <h6 className={styles.messageHead}>
                        Diane
                        <Image
                          src={smallTICK}
                          alt=""
                          className={styles.small_tick}
                        ></Image>
                      </h6>
                      <div className={styles.comman_msg}>
                        <p className={styles.message_para}>
                          Sent you a message
                        </p>
                        <span className={styles.timer}>54m</span>
                      </div>
                    </figcaption>
                  </div>
                </div>
                <div className={styles.messageBOX}>
                  <div className={styles.message_div}>
                    <figure>
                      <Image
                        src={message_profile}
                        alt=""
                        className={styles.message_profile}
                      ></Image>
                    </figure>
                    <figcaption className="w-100">
                      <h6 className={styles.messageHead}>
                        Diane
                        <Image
                          src={smallTICK}
                          alt=""
                          className={styles.small_tick}
                        ></Image>
                      </h6>
                      <div className={styles.comman_msg}>
                        <p className={styles.message_para}>
                          Sent you a message
                        </p>
                        <span className={styles.timer}>54m</span>
                      </div>
                    </figcaption>
                  </div>
                </div>

                <div className={styles.messageBOX}>
                  <div className={styles.message_div}>
                    <figure>
                      <Image
                        src={message_profile}
                        alt=""
                        className={styles.message_profile}
                      ></Image>
                    </figure>
                    <figcaption className="w-100">
                      <h6 className={styles.messageHead}>
                        Diane
                        <Image
                          src={smallTICK}
                          alt=""
                          className={styles.small_tick}
                        ></Image>
                      </h6>
                      <div className={styles.comman_msg}>
                        <p className={styles.message_para}>
                          Sent you a message
                        </p>
                        <span className={styles.timer}>54m</span>
                      </div>
                    </figcaption>
                  </div>
                </div>
                <div className={styles.messageBOX}>
                  <div className={styles.message_div}>
                    <figure>
                      <Image
                        src={message_profile}
                        alt=""
                        className={styles.message_profile}
                      ></Image>
                    </figure>
                    <figcaption className="w-100">
                      <h6 className={styles.messageHead}>
                        Diane
                        <Image
                          src={smallTICK}
                          alt=""
                          className={styles.small_tick}
                        ></Image>
                      </h6>
                      <div className={styles.comman_msg}>
                        <p className={styles.message_para}>
                          Sent you a message
                        </p>
                        <span className={styles.timer}>54m</span>
                      </div>
                    </figcaption>
                  </div>
                </div>
                <div className={styles.messageBOX}>
                  <div className={styles.message_div}>
                    <figure>
                      <Image
                        src={message_profile}
                        alt=""
                        className={styles.message_profile}
                      ></Image>
                    </figure>
                    <figcaption className="w-100">
                      <h6 className={styles.messageHead}>
                        Diane
                        <Image
                          src={smallTICK}
                          alt=""
                          className={styles.small_tick}
                        ></Image>
                      </h6>
                      <div className={styles.comman_msg}>
                        <p className={styles.message_para}>
                          Sent you a message
                        </p>
                        <span className={styles.timer}>54m</span>
                      </div>
                    </figcaption>
                  </div>
                </div>
                <div className={styles.messageBOX}>
                  <div className={styles.message_div}>
                    <figure>
                      <Image
                        src={message_profile}
                        alt=""
                        className={styles.message_profile}
                      ></Image>
                    </figure>
                    <figcaption className="w-100">
                      <h6 className={styles.messageHead}>
                        Diane
                        <Image
                          src={smallTICK}
                          alt=""
                          className={styles.small_tick}
                        ></Image>
                      </h6>
                      <div className={styles.comman_msg}>
                        <p className={styles.message_para}>
                          Sent you a message
                        </p>
                        <span className={styles.timer}>54m</span>
                      </div>
                    </figcaption>
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.right_chatbox}>
              <div className={styles.chatboxHEAD}>
                <figure>
                  <Image
                    src={yolanda1}
                    alt=""
                    className={styles.chatboxImage}
                  ></Image>
                </figure>
                <figcaption>
                  <h6 className={styles.chatboxHeading}>
                    Yolanda
                    <Image
                      src={smallTICK}
                      alt=""
                      className={styles.small_tick}
                    ></Image>
                  </h6>
                  <div className={styles.downpara}>
                    <span className={styles.chatboxpara}>Yolanda Official</span>
                  </div>
                </figcaption>
              </div>
              <span className={styles.lineHR}></span>
              {/* chatbox */}

              <form action="" className={styles.main_chatBox}>
                <div className={styles.wrap_chatleft}>
                  <div className={styles.left_ChatBOX}>
                    <span className={styles.left_chat}>thanks</span>
                  </div>{" "}
                  <p className={styles.chatBox_time}>2:33 PM</p>
                </div>
                <div className={styles.wrap_chatleft}>
                  <div
                    className={`${styles.left_ChatBOX} ${styles.leftwrapper}`}
                  >
                    <p className={styles.left_chat}>Lorem ipsum dolor sit consetetur</p>
                  </div>
                  <p className={styles.chatBox_time}>2:33 PM</p>
                </div>
                <div className={styles.wrap_chatRight}>
                <p className={styles.chatBox_time}>2:33 PM</p>
                  <div className={styles.right_CHATbox}>
                    <p className={styles.right_chat}>Lorem ipsum dolor sit consetetur</p>
                  </div>
                </div>
                <div className={styles.wrap_chatRight}>
                <p className={styles.chatBox_time}>2:33 PM</p>
                  <div className={styles.right_CHATbox}>
                  <span className= {styles.right_chat}>thanks</span>
                  </div>
                </div>

                {/* Comment Section */}
          <div className={styles.comment_section}>

          </div>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
