export const Constants = {
    ADDUSER: 'Signup',
    LOGINUSER: 'Login',
    LOGGED: 'LOGGEDIN',
    EDITRES: 'EDIT_PROFILES_API_STATUS',
    FORGOT:'FORGOTPASSWORD',
    VERIFICATIONRESEND: 'LOGIN_SIGNUP_VERIFICATION_RESEND',
    ADDUSER1: 'SignupOtp',
    LOGINUSER1:'loginOtp',
    GETDATA:'GETTING_CATEGORY_LIST',
    GETSUGGESTION:'GETTING_USER_SUGGESTION_LIST',
    GETCARD: 'GETTING_USER_CREATED_DATA',
    FOLLOW: 'FOLLOW_REQUEST_API',
    FEED: 'FEEDS_DATA',
    FOLLOWING: 'GET_FOLLOWING_LIST',
    FOLLOWER: 'GET_FOLLOWER_LIST',
    UNFOLLOW: 'UNFOLLOW_REQUEST_API',
    RESET: 'RESET_REDUCERS',
    POSTCOMMENT: 'POST_COMMENT_FEED',
    GETCOMMENT: 'GETTING_ALL_COMMENTS',
    LIKES: 'HIT_LIKE',
    CREATERESET: 'RESET_CREATED_REDUCER'
    // SUCCESS: 'ALERT_SUCCESS',
    // ERROR: 'ALERT_ERROR',
    // CLEAR: 'ALERT_CLEAR'
    
};
