export const MasterStatusCodes = [
  { STATUS_CODE: 1, STATUS_DESC: "Created" },
  { STATUS_CODE: 2, STATUS_DESC: "Deleted" },
  { STATUS_CODE: 3, STATUS_DESC: "Accepted" },
  { STATUS_CODE: 4, STATUS_DESC: "Approved" },
  { STATUS_CODE: 5, STATUS_DESC: "Sent Back by Seller Checker" },
  { STATUS_CODE: 6, STATUS_DESC: "Sent Back by Buyer Maker" },
  { STATUS_CODE: 7, STATUS_DESC: "Sent Back by Buyer Checker" },
  { STATUS_CODE: 8, STATUS_DESC: "Sent Back by Seller Maker" },
  { STATUS_CODE: 10, STATUS_DESC: "Rejected" },
  { STATUS_CODE: 12, STATUS_DESC: "Blocked in Star Validation" },
  { STATUS_CODE: 13, STATUS_DESC: "Blocked in Partner Dedupe Validation" },
  { STATUS_CODE: 16, STATUS_DESC: "Expired due to not accepting FU" },
  { STATUS_CODE: 23, STATUS_DESC: "Blocked in ATReDS Dedupe Validation" },
  { STATUS_CODE: 24, STATUS_DESC: "Rejected in ATReDS Dedupe Validation" },
  { STATUS_CODE: 25, STATUS_DESC: "Expired during ATReDS review" },
  { STATUS_CODE: 400, STATUS_DESC: "Pending Extraction for API Approval" },
  { STATUS_CODE: 401, STATUS_DESC: "Extracted but awaiting response" },
  { STATUS_CODE: 402, STATUS_DESC: "Accepted by CounterParty in the review" },
  { STATUS_CODE: 403, STATUS_DESC: "Rejected by CounterParty in the review" },
  { STATUS_CODE: 404, STATUS_DESC: "Expired" },
  { STATUS_CODE: 2100, STATUS_DESC: "FU Withdrawn" },
  { STATUS_CODE: 9, STATUS_DESC: "Authorisation" },
  { STATUS_CODE: 11, STATUS_DESC: "Bid Accepted" },
  { STATUS_CODE: 14, STATUS_DESC: "Expired due to not accepting bid" },
  { STATUS_CODE: 21, STATUS_DESC: "Expired - No Bid" },
  { STATUS_CODE: 15, STATUS_DESC: "Default FU" },
  { STATUS_CODE: 17, STATUS_DESC: "Financed" },
  { STATUS_CODE: 18, STATUS_DESC: "Expired due to Settlement 1 failure" },
  { STATUS_CODE: 19, STATUS_DESC: "Realised" },
  { STATUS_CODE: 20, STATUS_DESC: "Overdue" },
  { STATUS_CODE: 22, STATUS_DESC: "Settled outside of Treds" },
  { STATUS_CODE: 26, STATUS_DESC: "Disbursement Overdue" },
];
