import React from "react";
import AuthHeader from "../common/navigation/authHeader";
import styles from "../styles/about.module.css";
import Head from "next/head";
export default function About() {
  return (
    <div className="container">
          <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AuthHeader />
      <div className={styles.about_content}>
        <div className={styles.sub_about_content}>
          <h2 className={styles.about_heading}>Why We Do This</h2>
          <p className={styles.about_para}>
            NFTs are virtual tokens that represent ownership of something
            inherently distinct and scarce, whether it be a physical or digital
            item, such as artwork, a soundtrack, a collectible, an in-game item
            or real estate. Unlike regular cryptocurrencies like bitcoin or fiat
            money like the U.S.
          </p>
        </div>
        <div className={styles.sub_about_content}>
          <h2 className={styles.about_heading}>
            Helping You Grow In Every Stage.
          </h2>
          <p className={styles.about_para}>
            NFTs are virtual tokens that represent ownership of something
            inherently distinct and scarce, whether it be a physical or digital
            item, such as artwork, a soundtrack, a collectible, an in-game item
            or real estate. Unlike regular cryptocurrencies like bitcoin or fiat
            money like the U.S.
          </p>
        </div>
        <div className={styles.sub_about_content}>
          <h2 className={styles.about_heading}>
            Create, Sell well & Collect your Wonderful NFTs at SYN Very Fast
          </h2>
          <p className={styles.about_para}>
            The NFTs is a one-trick pony that climbed the ladders of success in
            recent years. The growth NFTs is tremendous, and according to
            Pymnts.com, the total sales volume of NFTs has nearly crossed $2.5
            billion in the last six months of 2021. Surprisingly, the total
            sales volume of NFTs was $13.7 million in 2020. On comparing both
            the values,
          </p>
        </div>
      </div>
    </div>
  );
}
