export const GETTING_USER_DETAILS = "GETTING_USER_DETAILS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAIL_SUCCESS = "UPDATE_USER_DETAIL_SUCCESS";
export const UPDATE_USER_DETAILS_FROM_FORM = "UPDATE_USER_DETAILS_FROM_FORM";
