import React, { useState } from "react";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Auth.module.css";
import forgotlogo from "../../public/images/forget_password.svg";
import { forgotValidation } from "../../helpers/helpers";
import { useDispatch } from "react-redux";
import { forgotAction } from "../../action";
import { ToastContainer } from "react-toastify";
const Forgotpassword = () => {
  const dispatch = useDispatch();
  const [email, setEmail] = useState("");
  //validation state:
  let isValid;
  const [error, setError] = useState("");
 // states toggle for api :
 const [isEmail, setIsEmail] = useState(false);
  //handling form validation:
  const validate = () => {
    const res = forgotValidation(email);
    setError(res.errors);
    isValid = res.formIsValid;
  };
  //handling change:
  function handleEmailChange(event) {
    setEmail(event.target.value);
    checkNumberOrEmail();
  }
  //function to check state:
function checkNumberOrEmail(){
  // console.log("inside email",email)
    //setEmail(text);
   // setIsFocused(true);
  if(!email.charAt(0).match(/^[A-Za-z]*$/)){
   setIsEmail(false)
  }
  if(email.charAt(0).match(/^[A-Za-z]*$/)){
    setIsEmail(true)
   }

}
  //form handlesubmit:
  const handleSubmit = (event) => {
    event.preventDefault();
    validate();
    checkNumberOrEmail();
    if (isValid == true) {
      if(isEmail == true){
      const userDetails = {
        email: email,
      };
      dispatch(forgotAction(userDetails));
    }
    else{
      const userDetails = {
       phone_no: email,
      };
      dispatch(forgotAction(userDetails));
      // console.log("userDETAILS7777777",userDetails)
    }
    }
  };
  return (
    <div>
      <div className={`${styles.maincontent}`}>
        <Head>
          <title>forgotPassword</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <div className={styles.loginFormWrapper}>
          {/* <div className={styles.container}> */}
            <div className={styles.loginForm}>
              <div
                className={`d-flex align-items-center justify-content-between`}
              >
                <div className={`d-flex align-items-center`}>
                  <Image
                    src={forgotlogo}
                    className={styles.Image1}
                    alt=""
                  ></Image>
                  <h4 className={styles.txtVerify}>Forget Password?</h4>
                </div>
                {/* <Image src={cross}></Image> */}
              </div>
              <div className={styles.loginHead}>
                <p className={styles.contentHead}>
                  Enter the email address or phone number associated with your
                  account.
                </p>
              </div>
             
                <span className={styles.line}></span>
           

              <form
                action=""
                className={styles.formMargin}
                onSubmit={handleSubmit}
              >
                <div>
                  <h3 className={styles.txtEnter}>Enter Email/ Phone Number</h3>
                 
                    <input
                      type="text"
                      placeholder="Email / Phone number"
                     // onChange={(e) => setEmail(e.target.value)}
                     onChange={handleEmailChange}
                      onKeyUp={validate}
                      // value="pamela.rivera@gmail.com"
                      className={styles.inputEmail}
                    />
                    {/* <span className={styles.errMsg}>Enter valid email</span> &nbsp; */}
                    {/* <span className={styles.errMsg}>Field can't be empty</span> */}
                  
                </div>
                <span id="span_email" className={styles.errMsg}>
                      {error["emailError"]}
                    </span>{" "}
                    &nbsp;
                <button type="Login" className={styles.loginButton2}>Submit</button>
              </form>

            
                <div className={styles.bottomLink}>
                  <Link href="/auth/login">
                    <a className={styles.signUp}>Back to login</a>
                  </Link>
                
              </div>
            </div>
          {/* </div> */}
        </div>
      </div>
      <ToastContainer />
    </div>
  );
};
export default Forgotpassword;


