import React from 'react'
import Image from 'next/image'
import styles from "../../styles/Auth.module.css"
import passwordreset from "../../public/images/password_reset.svg"
import Head from 'next/head'
import Link from 'next/link'

export default function ResetPassword() {
  return (
    <div>
        <div className={styles.maincontent}>
        <Head>
          <title>Set new password</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <div className={styles.loginFormWrapper}>
        {/* <div className={styles.container}> */}

        <div className={styles.loginForm}>
        <div
                className={`d-flex align-items-center justify-content-between`}
              >
                <div className={`d-flex align-items-center`}>
                  <Image src={passwordreset} className={styles.Image1} alt=""></Image>
                  <h4 className={styles.txtVerify}>Password Reset</h4>
                </div>
                {/* <Image src={cross}></Image> */}
              </div>
              <div className={styles.loginHead}>
                <p className={styles.contentHead}>
                Your password has been successfully reset. Click below to log in magically.
                </p>
              </div>
              <Link href={'/auth/login'}>
              <button
                type="Login"
                className={`${styles.verifyButton} btn btn-primary`}
              >
                Login
              </button>
              </Link>
        </div>
        {/* </div> */}
        </div>
        </div>
    </div>
  )
}
