import React from "react";
import styles from "../../../styles/dashboardprofile.module.css";
import Head from "next/head";
import Link from "next/link";
import Router from "next/router";
import { googleOAuthLogout, signupOtpAction } from "../../../action";
import { useGoogleLogout } from "react-google-login";
import { useDispatch } from "react-redux";
export default function Logout() {
   //accessing google client id:
   let clientId = process.env.GOOGLE_ID;
   const dispatch = useDispatch()
  const handleLogOut=()=>{
    localStorage.clear();
    sessionStorage.clear();
   // signOut()

   // Router.push('/')
    window.location.href='/'
  }
   //google login function:
  const onLogoutSuccess = (res) => {
    dispatch(googleOAuthLogout(res));
    localStorage.clear();
    sessionStorage.clear();
    window.location.href='/'
  };
  const onFailure = (res) => {
    dispatch(googleOAuthLogout(res));
    localStorage.clear();
    sessionStorage.clear();
    //window.location.href='/'
  };
  const { signOut} =useGoogleLogout({
    onLogoutSuccess,
    onFailure,
    clientId,
  });
  return (
    <div className={styles.main_container}>
        <Head>
            <title>Head</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
      <div className="container">
        <div className={styles.main_popup}>
        <div className={styles.popup}>
          {/* <h6 className={styles.logoutHead}>Are you sure?</h6> */}
          <p className={styles.logoutHead}>Are you sure want to sign out ?</p>
          <div className={styles.logoutBTN}>
          {/* <Link href='/'> */}
            <button type="button" className={styles.yesBTN} onClick={signOut}>
              Yes
            </button>
            {/* </Link> */}
            <Link href="/dashboard/home">
            <button type="button" className={styles.CancleBTN}>
              Cancel
            </button>
            </Link>     
          </div>
        </div>
        </div>
      </div>
    </div>
  );
}
