import React from "react";
import styles from "../../../styles/exploreCollection.module.css";
import Image from "next/image";
import close from "../../../public/images/close2.svg";
import Head from "next/head";
import withAuth from "../../../helpers/hoc";

 function BuyNow() {
  return (
    <div className="container">
      <Head>
      <title>Buy Now</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <form action="" className={styles.formBuynow}>
        <div className={styles.checkoutDiv}>
          <div className={styles.sub_main_div}>
            <div className={styles.upperSection_checkout}>
              <h2 className={styles.checkout_head}>Checkout</h2>
              <Image src={close} className={styles.close}></Image>
            </div>

            <p className={styles.para_checkout}>
              You are about to purchase a from{" "}
              <a href="" className={styles.para_checkout_clr}>
                AnimeSailorClub{" "}
              </a>{" "}
              <a href="" className={styles.para_checkout_clr}>
                Yolanda
              </a>
            </p>
            <h6 className={styles.quantity_text}>
              Enter quantity.{" "}
              <span className={styles.quantity_text_clr}>10 available</span>
            </h6>
            <input
              type="text"
              className={styles.checkoutInput}
              placeholder={1}
            />
            <div className={styles.pay_div}>
              <div className={styles.sub_div}>
                <h6 className={styles.bln_text}>Your balance</h6>
                <h6 className={styles.bln_ETH}>10.67856 ETH</h6>
              </div>

              <div className={styles.sub_div}>
                <h6 className={styles.bln_text}>Service fee 2.5%</h6>
                <h6 className={styles.bln_ETH}>0.00325 ETH</h6>
              </div>

              <div className={styles.sub_div}>
                <h6 className={styles.bln_text}>You will pay</h6>
                <h6 className={styles.bln_ETH}>0.013325 ETH</h6>
              </div>
            </div>
            <div className={styles.funds}>
              <button className={styles.addfundBTN}>Add Funds</button>
            </div>
          </div>
        </div>
      </form>
    </div>
  );
}
export default withAuth (BuyNow)
